name: Build with Tests

on: [push]

jobs:
  build_and_test_Windows:
    name: Build and run Tests on Windows
    runs-on: windows-latest

    env:
      IsRunningOnGitHubActions: 'true'
      UseInMemory: 'true'

    steps:  
    - uses: actions/checkout@v4
              
    - name: Build
      run: |
        dotnet build ./src/System.Linq.Dynamic.Core/System.Linq.Dynamic.Core.csproj -c Release -p:buildType=azure-pipelines-ci

    - name: Run Tests EFCore .NET 8
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.Tests/System.Linq.Dynamic.Core.Tests.csproj -c Release -p:buildType=azure-pipelines-ci

    - name: Run Tests Json .NET 8
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.NewtonsoftJson.Tests/System.Linq.Dynamic.Core.NewtonsoftJson.Tests.csproj -c Release -f net8 -p:buildType=azure-pipelines-ci
        dotnet test ./test/System.Linq.Dynamic.Core.SystemTextJson.Tests/System.Linq.Dynamic.Core.SystemTextJson.Tests.csproj -c Release -f net8 -p:buildType=azure-pipelines-ci

  build_and_test_Linux:
    name: Build and run Tests on Linux
    runs-on: ubuntu-latest

    env:
      IsRunningOnGitHubActions: 'true'

    steps:  
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: |
         6.0.x
         7.0.x
         8.0.x
              
    - name: Build
      run: |
        dotnet build ./src/System.Linq.Dynamic.Core/System.Linq.Dynamic.Core.csproj -c Release -p:buildType=azure-pipelines-ci

    - name: Run Tests Json .NET 8
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.NewtonsoftJson.Tests/System.Linq.Dynamic.Core.NewtonsoftJson.Tests.csproj -c Release -f net8 -p:buildType=azure-pipelines-ci
        dotnet test ./test/System.Linq.Dynamic.Core.SystemTextJson.Tests/System.Linq.Dynamic.Core.SystemTextJson.Tests.csproj -c Release -f net8 -p:buildType=azure-pipelines-ci

    - name: Run Tests EF .NET 8
      run: |
        dotnet test ./test/EntityFramework.DynamicLinq.Tests/EntityFramework.DynamicLinq.Tests.csproj -c Release -f net8.0 -p:buildType=azure-pipelines-ci

    - name: Run Tests EFCore .NET 8
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.Tests/System.Linq.Dynamic.Core.Tests.csproj -c Release -p:buildType=azure-pipelines-ci

    - name: Run Tests EFCore .NET 7
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.Tests.Net7/System.Linq.Dynamic.Core.Tests.Net7.csproj -c Release -p:buildType=azure-pipelines-ci

    - name: Run Tests EFCore .NET 6
      run: |
        dotnet test ./test/System.Linq.Dynamic.Core.Tests.Net6/System.Linq.Dynamic.Core.Tests.Net6.csproj -c Release -p:buildType=azure-pipelines-ci